Unit-Tests
INM-6/lif_meanfield_tools pull request #48
Opened 2020-05-26 09:39 UTC by moritzlayer

Add a unit test suite for all files in lif_meanfield_tools written with pytest.

I took the unit tests for input_output.py incorporated in Simon's pull request #34 and merged them into this one.

2020-06-03 14:10 UTC, essink commented on tests/fixtures/config/analysis_params_test.yaml
> +  # 1/(2*pi)
This comment can be deleted.

2020-06-04 14:08 UTC, essink commented on tests/unit/test_meanfield_calcs.py
> +        # import pdb; pdb.set_trace()
Delete debugging remainder.

```suggestion
```

2020-06-04 14:16 UTC, essink commented on pytest.ini
> +norecursedirs = .* lif_meanfield_tools example *.egg dist build
I think, I don't really understand what it does: Does it tell pytest which directories should not recurse into?

If yes one could add:
`readme_figures`

and maybe change
```suggestion
norecursedirs = .* lif_meanfield_tools example *.egg* dist build
```
to cover `.egg-info`, which exists in my case.

2020-10-26 09:56 UTC, jhnnsnk requested changes
Thanks for this extensive test suite.
Before merging, please add some documentation about how to use the tests in the README and add a file specifying the environment (without prefix).

2020-10-29 14:19 UTC, moritzlayer commented on tests/fixtures/config/analysis_params_test.yaml
> +  # 1/(2*pi)
done

2020-10-29 14:27 UTC, moritzlayer commented on tests/fixtures/create_fixtures.py
> +WARNING: Only use this script, if your code is trustworthy! The script runs
You are right, but then I will keep it for now.

2020-10-29 14:28 UTC, moritzlayer commented on tests/unit/test_network.py
> +result_ids = sorted(result_types.keys())
Done

2020-10-29 14:34 UTC, moritzlayer commented on pytest.ini
> +norecursedirs = .* lif_meanfield_tools example *.egg dist build
Yes, you're right. These are the paths that are excluded during test collection. `.egg-info` is already excluded due to the `.*` expression.  I will add `readme_figures` though.

2020-10-29 14:39 UTC, moritzlayer commented on tests/unit/test_input_output.py
> +    def test_save_and_load_existing_results_with_anlysis_params(
It is amazing that you found that!

2020-10-29 16:14 UTC, moritzlayer commented on tests/unit/test_meanfield_calcs.py
> +    # Def function as staticmethod because it is not tightly related to class,
Done

2020-10-29 16:20 UTC, moritzlayer commented on tests/unit/test_input_output.py
> +            with pytest.raises(IOError):
Converted into an issue

2020-10-29 16:59 UTC, moritzlayer commented
I added some documentation to the `README.md`, an `environment.yaml`, and I integrated Simon's suggestions.

2020-11-09 14:10 UTC, jhnnsnk commented on README.md
> +run all the tests, you can simply do so by installing and activating the conda environment specified in the provided `environmen.yaml` file, and running
Fix environment.yaml with a t.

2020-11-09 14:14 UTC, jhnnsnk commented on README.md
> +to the class for later reference. This allows calling function as an 'unbound function', without passing the instance to the function:
"to allow **sb.** to do sth.", also below

2020-11-09 14:15 UTC, jhnnsnk commented on README.md
> +
I think it would be good to comment on why some tests fail and that failure is unequal to an error.

2020-11-09 14:21 UTC, jhnnsnk requested changes
Thanks for addressing my comments. I can confirm that everything runs through with the new environment.
I only have some minor further requests regarding the documentation.

2020-11-17 12:08 UTC, jhnnsnk approved these changes
Thank you, looks all great now! :+1:

2020-11-17 13:19 UTC, merged